@backend_HostAddress = http://localhost:5170


GET {{backend_HostAddress}}/api/usres
Accept: application/json

### Pobieranie wszystkich użytkowników
GET {{backend_HostAddress}}/api/users

### Dodawanie użytkownika
POST {{backend_HostAddress}}/api/users
Content-Type: application/json

{
  "username": "Kasia",
  "email": "kasia.mail",
  "passwordHash": "testpass"
}

### Usuwanie użytkownika

### Pobieranie wszystkich wycieczek
GET {{backend_HostAddress}}/api/trips

### Pobieranie wycieczek o id 1
GET {{backend_HostAddress}}/api/trips/1

### Pobieramy wycieczku użytkownika o id 1
GET {{backend_HostAddress}}/api/trips/user/1


### Dodawanie wycieczek
POST {{backend_HostAddress}}/api/trips
Content-Type: application/json

{
  "username": "Kasia",
  "email": "kasia.mail",
  "passwordHash": "testpass"
}

### sprawdzanie logowania:
POST {{backend_HostAddress}}/api/login
Content-Type: application/json

{
  "username": "Kasia",
  "password": "testpass"
}



### Rejestracja użytkownika
POST {{backend_HostAddress}}/api/register
Content-Type: application/json

{
  "username": "ba",
  "email": "bb@.mail",
  "password": "abba"
}

### Logowanie tego użytkownika

POST {{backend_HostAddress}}/api/login
Content-Type: application/json

{
  "username": "ba",
  "password": "abba"
}
