@backend_HostAddress = http://localhost:5170

GET {{backend_HostAddress}}/api/usres
Accept: application/json

### Pobieranie wszystkich użytkowników
GET {{backend_HostAddress}}/api/users

### Dodawanie użytkownika
POST {{backend_HostAddress}}/api/users
Content-Type: application/json

{
  "username": "Kasia",
  "email": "kasia.mail",
  "passwordHash": "testpass"
}

### Usuwanie użytkownika
DELETE https://localhost:5001/api/users/3

### Pobieranie wszystkich wycieczek
GET {{backend_HostAddress}}/api/trips

### Pobieranie wycieczek o id 1
GET {{backend_HostAddress}}/api/trips/1

### Pobieramy wycieczku użytkownika o id 1
GET {{backend_HostAddress}}/api/trips/user/1


### Dodawanie wycieczek
POST {{backend_HostAddress}}/api/trips
Content-Type: application/json

{
    "destination": "Barcelona",
    "startDate": "2024-12-20T00:00:00",
    "endDate": "2024-12-27T00:00:00",
    "budget": 2000.00,
    "userId": 2
}

